openapi: 3.0.0
info:
  title: simple-api
  version: 0.1.0

paths:
  /hello:
    get:
      responses:
        '200':
          description: A simple hello world!
          content:
            text/plain:
              schema:
                type: string
              example: Hello from a mocked response!
      x-kusk:
        upstream:
          service:
            name: hello-world-svc
            namespace: default
            port: 8080