@startuml
!include <C4/C4_Component>

Container(backend, "Бэкенд API", "Java") {
Component(heating_control, "Управление отоплением", "Java", "Управление и контроль системы отопления")
Component(lighting_control, "Управление освещением", "Java", "Управление и контроль системы освещения")
Component(home_access_control, "Управление доступом к дому", "Java", "Управление доступом к дому и контроль безопасности")
Component(video_surveillance, "Видеонаблюдение", "Java", "Управление видеонаблюдение")
Component(device_management, "Управление устройствами", "Java", "Управление устройствами и их конфигурацией")
Component(automation_scenarios, "Управление сценариями автоматизации", "Java", "Обработка и выполнение сценариев автоматизации")
Component(partners, "Управление интеграциями с партнёрами", "Java", "Управление интеграциями с партнерскими устройствами и сервисами")
Component(auth, "Пользователи", "Java", "Аутентификация и авторизация пользователей")
Component(notification, "Уведомления", "Java", "Управление и отправка уведомлений")
Component(payment_service, "Платежи", "Java", "Обработка платежей и управление биллингом")
Component(support, "Клиентская поддержка", "Java", "Обработка обращений пользователей и управление поддержкой")
Component(subscription, "Управление подписками", "Java", "Управление подписками и тарифными планами")
}

ContainerDb(home_access_control_database, "База данных", "PostgreSQL", "Хранение истории доступа к дому")
ContainerDb(video_surveillance_database, "База данных", "PostgreSQL", "Хранение информации о видеозаписях")
ContainerDb(video_surveillance_s3, "Хранилище", "S3", "Хранение видеозаписей")
ContainerDb(device_management_database, "База данных", "PostgreSQL", "Хранение информации об устройствах пользователей")
ContainerDb(automation_scenarios_database, "База данных", "PostgreSQL", "Хранение сценариев автоматизации")
ContainerDb(partners_database, "База данных", "PostgreSQL", "Хранение датчиков и систем партнеров")
ContainerDb(auth_database, "База данных", "PostgreSQL", "Хранение пользователей")
ContainerDb(notification_database, "База данных", "PostgreSQL", "Хранение шаблонов уведомлений")
ContainerDb(payment_database, "База данных", "PostgreSQL", "Хранение статусов платежей")
ContainerDb(support_database, "База данных", "PostgreSQL", "Хранение обращений пользователей")
ContainerDb(subscription_database, "База данных", "PostgreSQL", "Хранение подписок")

System_Ext(email, "Email-сервис", "Отправка уведомлений")
System_Ext(payment, "Платежный шлюз", "Обработка платежей.")
System_Ext(partner, "Парнерские системы", "Датчики и системы умного дома")

Rel(home_access_control, home_access_control_database, "JDBC")
Rel(video_surveillance, video_surveillance_database, "JDBC")
Rel(video_surveillance, video_surveillance_s3, "HTTP")
Rel(device_management, device_management_database, "JDBC")
Rel(automation_scenarios, automation_scenarios_database, "JDBC")
Rel(partners, partners_database, "JDBC")
Rel(notification, notification_database, "JDBC")
Rel(payment_service, payment_database, "JDBC")
Rel(support, support_database, "JDBC")
Rel(subscription, subscription_database, "JDBC")
Rel(auth, auth_database, "JDBC")

Rel(notification, email, "Направляет уведомление", "SMTP")
Rel(payment_service, payment, "Направляет на выполнение платежа", "HTTP")
Rel(partner, partners, "Управляют датчиками через кабинет партнера", "HTTP")
@enduml